site_name: cookiecutter-pytorch-lightning
repo_url: https://github.com/foreverYoungGitHub/cookiecutter-pytorch-lightning
site_url: https://foreveryounggithub.github.io/cookiecutter-pytorch-lightning
site_description: A cookiecutter template for Python projects that use uv for its dependency management
site_author: Yang Liu
edit_uri: edit/main/docs/
repo_name: foreverYoungGitHub/cookiecutter-pytorch-lightning
copyright: Maintained by <a href="https://foreveryounggithub.github.io/">Yang</a>.

nav:
  - Home: index.md
  - Python Features:
      - CI/CD with Github Actions: features/cicd.md
      - Linting & code quality: features/linting.md
      - Makefile: features/makefile.md
      - Dependency management with uv: features/uv.md
      - Publishing to PyPI: features/publishing.md
      - Testing with Pytest: features/pytest.md
      - Test coverage with codecov: features/codecov.md
      - Documentation with MkDocs: features/mkdocs.md
      - Compatibility testing with Tox: features/tox.md
      - Containerization with Docker or Podman: features/docker.md
      - Devcontainer with VSCode: features/devcontainer.md
  - Deep Learning Features:
      - Setup environment: dl_features/environment.md
      - Tutorials: dl_features/tutorials.md
      - Superpowers: dl_features/superpowers.md
      - Training: dl_features/training.md
      - Evaluation: dl_features/evaluation.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md
plugins:
  - search
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  feature:
    tabs: true
  palette:
    # Note: Using the system theme works with the insiders version
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: astral-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: astral-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/foreverYoungGitHub/cookiecutter-pytorch-lightning
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cookiecutter-pytorch-lightning/
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
